### ISSUE TITLE
interpolation matrix

### ISSUE THREAD

**Issue by rveltz** [JuliaApproximation/BasisFunctions.jl#4]
Hi,

I am trying to find the interpolation matrix for Chebychev basis but I am getting lost. Basically, given a basis `B` of length N and a set of P points `x`, how do  I get the P x N interpolation matrix?

Thank you for your help,

Bests.

**Comment by vincentcp** [comment]
Hi, 

I understand that the lack of documentation leads to a piece of code that is quite intimidating and unfriendly to analyse. Here how we create interpolation operators: 

```julia 
julia> using BasisFunctions


julia> B = ChebyshevT(10)
Chebyshev polynomials (first kind)
    ↳ length = 10
    ↳ Float64 -> Float64
    ↳ support = -1.0..1.0 (Chebyshev)



julia> x = ChebyshevNodes(10)
10-element ChebyshevTNodes{Float64}:
 -0.9876883405951378 
 -0.8910065241883679 
 -0.7071067811865476 
 -0.45399049973954686
 -0.15643446504023092
  0.1564344650402306 
  0.45399049973954675
  0.7071067811865475 
  0.8910065241883678 
  0.9876883405951377 

julia> evaluation_operator(B,x)
Operator iDCT * D

iDCT	:	FFTW in-place IDCT (DCT-III) plan for 10-element array of Float64
D	:	Diagonal operator with element type Float64
		    ↳ [3.1622776601683795, -2.23606797749979, 2.23606797749979  …  -2.23606797749979, 2.23606797749979, -2.23606797749979]
```
Note that the result here is an operator not an array.

**Comment by rveltz** [comment]
Thank you. I was not complaining! I know it is already long enough to do the code, yet to document it.

**Comment by vincentcp** [comment]
Thank you for that comment! I was just repeating my own thoughts if I have to debug some of the errors that appear in `BasisFunctions` ;)
