### ISSUE TITLE
2-arg `similar` of `IndexMatrix` doesn't create a mutable matrix

### ISSUE THREAD

**Issue by dkarrasch** [JuliaApproximation/BasisFunctions.jl#54]
I came across an issue in this nanosoldier run: https://github.com/JuliaLang/julia/pull/47683#issuecomment-1327011619, the error message is as follows:

```julia
Error During Test at /home/pkgeval/.julia/packages/BasisFunctions/BzAlj/test/util/test_utilities.jl:26
  Test threw exception
  Expression: D * E == Matrix(D) * Matrix(E)
  CanonicalIndexError: setindex! not defined for BasisFunctions.IndexMatrix{Float64, true, 1, UnitRange{Int64}}
  Stacktrace:
    [1] error_if_canonical_setindex(::IndexCartesian, ::BasisFunctions.IndexMatrix{Float64, true, 1, UnitRange{Int64}}, ::Int64, ::Int64)
      @ Base ./abstractarray.jl:1407
    [2] setindex!
      @ ./abstractarray.jl:1396 [inlined]
    [3] macro expansion
      @ /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/diagonal.jl:281 [inlined]
    [4] macro expansion
      @ ./simdloop.jl:77 [inlined]
    [5] __muldiag!
      @ /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/diagonal.jl:280 [inlined]
    [6] _muldiag!
      @ /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/diagonal.jl:352 [inlined]
    [7] mul!
      @ /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/diagonal.jl:365 [inlined]
    [8] mul!
      @ /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/matmul.jl:276 [inlined]
    [9] *(D::LinearAlgebra.Diagonal{Int64, UnitRange{Int64}}, A::BasisFunctions.IndexMatrix{Float64, true, 1, UnitRange{Int64}})
      @ LinearAlgebra /opt/julia/share/julia/stdlib/v1.10/LinearAlgebra/src/diagonal.jl:251
```

The issue is caused by changing diagonal multiplication to call 2-arg `similar` for the allocation of the target array (as is already implemented for division). I think that is the right thing to do, given that multiplication by a diagonal should preserve the array type, whereas 3-arg `similar` typically creates a dense `Array`. So, the options are to reconsider 2-arg `similar` for `IndexMatrix` to yield a mutable array as promised by the `similar` documentation, or catch multiplication and division by `Diagonal`s and make it call 3-arg `similar`, as is already done for `HermOrSym`.

**Comment by daanhb** [comment]
Thanks for following up on that nanosoldier run. This error should not concern you in LinearAlgebra whatsoever: it is simply an error for our `IndexMatrix` type to implement `similar` and return an `IndexMatrix`, as the result is always non-mutable. I'll remove this functionality.

**Comment by daanhb** [comment]
Done, thanks again for reporting
