### ISSUE TITLE
FillArrays compat very tight

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaApproximation/BasisFunctions.jl#56]
I noticed the FillArrays compat is very tight, which is causing some package resolution issues for me in a package that depends directly on BasisFunctions. Any chance you can loosen that?

**Comment by daanhb** [comment]
Sure, I notice that FillArrays is well past version 1 now. Any chance you know that version 1 will work with BasisFunctions? It probably does.

**Comment by daanhb** [comment]
Looks like it works. I had to upgrade GridArrays.jl first. New release later tonight

**Comment by daanhb** [comment]
Fixed in v0.6.4
